name: manga_easy_sdk
description: Kit de desenvolvimento da Mangá Easy.
publish_to: none
version: 1.5.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  intl: ^0.18.0
  logger: ^1.4.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
